add_subdirectory(base)
add_subdirectory(trust)
add_subdirectory(protocol)
add_subdirectory(platform)
add_subdirectory(symbols)
add_subdirectory(compatibility)
add_subdirectory(injector)
add_subdirectory(agent)
add_subdirectory(watchdog/protocol)
add_subdirectory(host)
add_subdirectory(watchdog)
add_subdirectory(cli)
